"""Изменено поле created_at с учётом часового пояса

Revision ID: a0244b91cad5
Revises: 126ee11862d5
Create Date: 2025-02-15 14:38:47.818581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0244b91cad5'
down_revision: Union[str, None] = '126ee11862d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_id', table_name='user')
    op.drop_index('ix_user_name', table_name='user')
    op.drop_index('ix_user_organiztion', table_name='user')
    op.drop_index('ix_user_sername', table_name='user')
    op.drop_index('ix_user_username', table_name='user')
    op.drop_table('user')
    op.drop_index('ix_incident_description', table_name='incident')
    op.drop_index('ix_incident_id', table_name='incident')
    op.drop_index('ix_incident_location', table_name='incident')
    op.drop_table('incident')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incident',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='incident_pkey')
    )
    op.create_index('ix_incident_location', 'incident', ['location'], unique=False)
    op.create_index('ix_incident_id', 'incident', ['id'], unique=False)
    op.create_index('ix_incident_description', 'incident', ['description'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('sername', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('organiztion', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('role', postgresql.ENUM('admin', 'user', name='roleenum'), autoincrement=False, nullable=True),
    sa.Column('telegram_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_pkey'),
    sa.UniqueConstraint('telegram_id', name='user_telegram_id_key')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_sername', 'user', ['sername'], unique=False)
    op.create_index('ix_user_organiztion', 'user', ['organiztion'], unique=False)
    op.create_index('ix_user_name', 'user', ['name'], unique=False)
    op.create_index('ix_user_id', 'user', ['id'], unique=False)
    # ### end Alembic commands ###
